// build.rs
use std::env;
use std::path::PathBuf;
use std::fs;

// ============================================================================
// Macro metadata-driven build script
//
// Independent constant macros (literal values, no references to other macros)
// are handled by bindgen via allowlist_var. The macro parser provides the list of
// independent macro names in constant_macros.json. bindgen performs type
// inference and generates pub const bindings.
//
// Dependent constant macros (referencing other macros) are NOT handled here.
// They are translated by the LLM as pub const bindings that preserve
// reference relationships.
//
// Flag macros are registered as cargo:rustc-cfg flags.
// ============================================================================

use serde::Deserialize;

/// Top-level structure of constant_macros.json produced by the macro parser.
/// Only independent macro names are needed here; dependent macros are
/// handled by the LLM during translation.
#[derive(Debug, Deserialize)]
struct MacroMeta {
    independent: Vec<String>,
    // dependent is intentionally omitted — handled by LLM prompts
}

/// Top-level structure of flag_macros.json produced by the macro parser.
#[derive(Debug, Deserialize)]
struct FlagMeta {
    flags: Vec<String>,
}

fn main() {
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());

    // ------------------------------------------------------------------
    // 0. Header paths (populated by the preprocessing step)
    // ------------------------------------------------------------------
    let config_paths: Vec<&str> = vec![
    ];
    
    for path in &config_paths {
        println!("cargo:rerun-if-changed={}", path);
    }

    // ------------------------------------------------------------------
    // 1. Read macro metadata
    // ------------------------------------------------------------------
    println!("cargo:rerun-if-changed=// CONST_MACRO_PATH_PLACEHOLDER");
    println!("cargo:rerun-if-changed=// FLAG_MACRO_PATH_PLACEHOLDER");

    let macro_meta: MacroMeta = {
        let raw = fs::read_to_string("// CONST_MACRO_PATH_PLACEHOLDER")
            .expect("Failed to read constant_macros.json — run the macro parser first");
        serde_json::from_str(&raw)
            .expect("Failed to parse constant_macros.json")
    };

    let flag_meta: FlagMeta = match fs::read_to_string("// FLAG_MACRO_PATH_PLACEHOLDER") {
        Ok(raw) => serde_json::from_str(&raw)
            .expect("Failed to parse flag_macros.json"),
        Err(_) => FlagMeta { flags: vec![] },
    };

    // ------------------------------------------------------------------
    // 2. Register flag macros as cfg flags
    // ------------------------------------------------------------------
    for flag in &flag_meta.flags {
        println!("cargo:rustc-cfg=has_{}", flag);
    }

    // ------------------------------------------------------------------
    // 3. Run bindgen with allowlist_var for independent macros only
    //
    //    - Independent macros: allowlisted → bindgen emits pub const
    //      with correct type inference
    //    - All other macros: Ignored via IndependentOnlyFilter
    //    - Functions, types, structs: also generated by bindgen as usual
    // ------------------------------------------------------------------
    let mut all_bindings = String::new();
    let mut seen_macros = std::collections::HashSet::new();
    let clang_args_json = fs::read_to_string("// CLANG_ARGS_JSON_PATH_PLACEHOLDER").unwrap_or_else(|_| "{}".to_string());
    let file_clang_args: std::collections::HashMap<String, Vec<String>> = serde_json::from_str(&clang_args_json).unwrap_or_default();

    if !config_paths.is_empty() {

        for path in &config_paths {
            let mut builder = bindgen::Builder::default();
            builder = builder.header(*path);
        
            if let Some(args) = file_clang_args.get(*path) {
                for arg in args {
                    builder = builder.clang_arg(arg);
                }
            }

            builder = builder.blocklist_function(".*");
            builder = builder.blocklist_type(".*");
            builder = builder.blocklist_function("main");

            // Allowlist only independent macros as vars.
            // bindgen treats #define constants as "vars", so allowlist_var
            // controls which macros get emitted as pub const.
            for name in &macro_meta.independent {
                builder = builder.allowlist_var(name);
            }

            // Use allowlist_recursively(false) to avoid pulling in
            // transitive type dependencies that we don't need.
            builder = builder.allowlist_recursively(false);
            builder = builder.parse_callbacks(Box::new(bindgen::CargoCallbacks::new()));

            match builder.generate() {
                Ok(bindings) => {
                    for line in bindings.to_string().lines() {
                        if line.starts_with("pub const") {
                            let name = line.split(':').next()
                                .unwrap_or("")
                                .trim()
                                .trim_start_matches("pub const ")
                                .trim();
                            if seen_macros.insert(name.to_string()) {
                                all_bindings.push_str(line);
                                all_bindings.push('\n');
                            }
                        }
                    }
                }
                Err(e) => {
                    println!("cargo:warning=bindgen generation failed for {}: {}", path, e);
                }
            }
        }
    }

    let bindings_path = out_path.join("bindings.rs");
    fs::write(&bindings_path, &all_bindings)
        .expect("Couldn't write bindings.rs");
}